import { Geist, Geist_Mono, Roboto_Slab } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});


export const metadata = {
  title: "Tiles Gallery Project",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html data-theme="light"
      lang="en"
      className={`${robotoSlab.variable} h-full antialiased`}>
      
      <body className={`${robotoSlab.variable} min-h-full flex flex-col`}>
        <main>{children}</main>
        <ToastContainer />
      </body>

    </html>
  );
}

